In [3]:
import numpy as np
import pandas as pd

### Some array practice

In [4]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

What 'shape' is this array?

In [5]:
x.shape

(3, 3)

What index is the '1'?

In [6]:
x[0,0]

1

Print eveyr colum in the second row.

In [7]:
x[1,:]

array([4, 5, 6])

Print every row in the last column

In [8]:
x[:,2]

array([3, 6, 9])

In [9]:
x[:,-1]

array([3, 6, 9])

Make a new (2 x 2) array from this one which has just the first two rows and first two columns in it.

Print this new array.

In [10]:
y=x[0:2,0:2]

In [11]:
print(y)

[[1 2]
 [4 5]]

### Some Dataframe practice

In [12]:
# This is just some code to make a DF which we will use for practice

def func_makedata(a):
    ''' this is just a function to make some data
    for our spreasheet (or 'dataframe') - you can happily ignore this
    '''
    x1 = a**2
    y1 = np.cos(a)
    z1 = 3*a**2
    return x1, y1, z1

aa = np.linspace(0.,10.,5)
x1, y1, z1 = func_makedata(aa)

data_dict = {}
data_dict['aa'] = aa
data_dict['x1'] = x1
data_dict['y1'] = y1
data_dict['z1'] = z1

# Here I am making a dataframe from arays which have been put into a dictionary
# you don't need to know at this stage what a 'dictionary' is.
df = pd.DataFrame(data_dict)
df

     aa      x1        y1      z1
0   0.0    0.00  1.000000    0.00
1   2.5    6.25 -0.801144   18.75
2   5.0   25.00  0.283662   75.00
3   7.5   56.25  0.346635  168.75
4  10.0  100.00 -0.839072  300.00

Print column 'aa'

In [13]:
df['aa']

0     0.0
1     2.5
2     5.0
3     7.5
4    10.0
Name: aa, dtype: float64

print the first element from column 'aa'

In [14]:
df['aa'][0]

0.0

if 'aa' == 0 print the df

In [15]:
boolean_index = df['aa']==0
print(boolean_index)

0     True
1    False
2    False
3    False
4    False
Name: aa, dtype: bool

In [16]:
df[boolean_index]

    aa   x1   y1   z1
0  0.0  0.0  1.0  0.0

if z1>100 then print the df

In [17]:
bi = df['z1']>100

In [18]:
print(bi)

0    False
1    False
2    False
3     True
4     True
Name: z1, dtype: bool

In [19]:
df[bi]

     aa      x1        y1      z1
3   7.5   56.25  0.346635  168.75
4  10.0  100.00 -0.839072  300.00